In [1]:
import sys
!{sys.executable} -m pip install google-cloud-bigquery db-dtypes pandas-gbq gcsfs

Requirement already satisfied: google-cloud-bigquery in /opt/anaconda3/lib/python3.12/site-packages (3.41.0)
Requirement already satisfied: db-dtypes in /opt/anaconda3/lib/python3.12/site-packages (1.6.0)
Requirement already satisfied: pandas-gbq in /opt/anaconda3/lib/python3.12/site-packages (0.35.0)
Requirement already satisfied: gcsfs in /opt/anaconda3/lib/python3.12/site-packages (2026.5.0)
Requirement already satisfied: google-api-core<3.0.0,>=2.11.1 in /opt/anaconda3/lib/python3.12/site-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (2.30.3)
Requirement already satisfied: google-auth<3.0.0,>=2.14.1 in /opt/anaconda3/lib/python3.12/site-packages (from google-cloud-bigquery) (2.53.0)
Requirement already satisfied: google-cloud-core<3.0.0,>=2.4.1 in /opt/anaconda3/lib/python3.12/site-packages (from google-cloud-bigquery) (2.6.0)
Requirement already satisfied: google-resumable-media<3.0.0,>=2.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from google-cloud-bigquery) (2.9.0)
Requirement already satisfied: packaging>=24.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from google-cloud-bigquery) (26.2)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.2 in /opt/anaconda3/lib/python3.12/site-packages (from google-cloud-bigquery) (2.9.0.post0)
Requirement already satisfied: requests<3.0.0,>=2.21.0 in /opt/anaconda3/lib/python3.12/site-packages (from google-cloud-bigquery) (2.32.2)
Requirement already satisfied: numpy>=1.24.0 in /opt/anaconda3/lib/python3.12/site-packages (from db-dtypes) (1.26.4)
Requirement already satisfied: pandas<3.0.0,>=1.5.3 in /opt/anaconda3/lib/python3.12/site-packages (from db-dtypes) (2.2.2)
Requirement already satisfied: pyarrow>=13.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from db-dtypes) (14.0.2)
Requirement already satisfied: setuptools in /opt/anaconda3/lib/python3.12/site-packages (from pandas-gbq) (69.5.1)
Requirement already satisfied: pydata-google-auth>=1.5.0 in /opt/anaconda3/lib/python3.12/site-packages (from pandas-gbq) (1.9.1)
Requirement already satisfied: psutil>=5.9.8 in /opt/anaconda3/lib/python3.12/site-packages (from pandas-gbq) (7.2.2)
Requirement already satisfied: google-auth-oauthlib>=0.7.0 in /opt/anaconda3/lib/python3.12/site-packages (from pandas-gbq) (1.4.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0 in /opt/anaconda3/lib/python3.12/site-packages (from gcsfs) (3.9.5)
Requirement already satisfied: decorator>4.1.2 in /opt/anaconda3/lib/python3.12/site-packages (from gcsfs) (5.1.1)
Requirement already satisfied: fsspec!=2026.4.0,>=2026.3.0 in /opt/anaconda3/lib/python3.12/site-packages (from gcsfs) (2026.3.0)
Requirement already satisfied: google-cloud-storage-control in /opt/anaconda3/lib/python3.12/site-packages (from gcsfs) (1.11.0)
Requirement already satisfied: google-cloud-storage>=3.9.0 in /opt/anaconda3/lib/python3.12/site-packages (from gcsfs) (3.10.1)
Requirement already satisfied: aiosignal>=1.1.2 in /opt/anaconda3/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->gcsfs) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in /opt/anaconda3/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->gcsfs) (23.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/anaconda3/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->gcsfs) (1.4.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/anaconda3/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->gcsfs) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in /opt/anaconda3/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->gcsfs) (1.9.3)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.63.2 in /opt/anaconda3/lib/python3.12/site-packages (from google-api-core<3.0.0,>=2.11.1->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (1.75.0)
Requirement already satisfied: protobuf<8.0.0,>=4.25.8 in /opt/anaconda3/lib/python3.12/site-packages (from google-api-core<3.0.0,>=2.11.1->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (6.33.6)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /opt/anaconda3/lib/python3.12/site-packages (from google-api-core<3.0.0,>=2.11.1->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (1.28.0)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /opt/anaconda3/lib/python3.12/site-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (1.80.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /opt/anaconda3/lib/python3.12/site-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (1.80.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/anaconda3/lib/python3.12/site-packages (from google-auth<3.0.0,>=2.14.1->google-cloud-bigquery) (0.2.8)
Requirement already satisfied: cryptography>=38.0.3 in /opt/anaconda3/lib/python3.12/site-packages (from google-auth<3.0.0,>=2.14.1->google-cloud-bigquery) (42.0.5)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /opt/anaconda3/lib/python3.12/site-packages (from google-auth-oauthlib>=0.7.0->pandas-gbq) (2.0.0)
Requirement already satisfied: google-crc32c<2.0.0,>=1.1.3 in /opt/anaconda3/lib/python3.12/site-packages (from google-cloud-storage>=3.9.0->gcsfs) (1.8.0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.12/site-packages (from pandas<3.0.0,>=1.5.3->db-dtypes) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.12/site-packages (from pandas<3.0.0,>=1.5.3->db-dtypes) (2023.3)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.12/site-packages (from python-dateutil<3.0.0,>=2.8.2->google-cloud-bigquery) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (2025.8.3)
Requirement already satisfied: grpc-google-iam-v1<1.0.0,>=0.14.0 in /opt/anaconda3/lib/python3.12/site-packages (from google-cloud-storage-control->gcsfs) (0.14.4)
Requirement already satisfied: cffi>=1.12 in /opt/anaconda3/lib/python3.12/site-packages (from cryptography>=38.0.3->google-auth<3.0.0,>=2.14.1->google-cloud-bigquery) (1.16.0)
Requirement already satisfied: typing-extensions~=4.12 in /opt/anaconda3/lib/python3.12/site-packages (from grpcio<2.0.0,>=1.33.2->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (4.15.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /opt/anaconda3/lib/python3.12/site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.14.1->google-cloud-bigquery) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.7.0->pandas-gbq) (3.3.1)
Requirement already satisfied: pycparser in /opt/anaconda3/lib/python3.12/site-packages (from cffi>=1.12->cryptography>=38.0.3->google-auth<3.0.0,>=2.14.1->google-cloud-bigquery) (2.21)

In [3]:
import sys
!{sys.executable} -m pip install google-cloud-bigquery db-dtypes pandas-gbq gcsfs

Requirement already satisfied: google-cloud-bigquery in /opt/anaconda3/lib/python3.12/site-packages (3.41.0)
Requirement already satisfied: db-dtypes in /opt/anaconda3/lib/python3.12/site-packages (1.6.0)
Requirement already satisfied: pandas-gbq in /opt/anaconda3/lib/python3.12/site-packages (0.35.0)
Requirement already satisfied: gcsfs in /opt/anaconda3/lib/python3.12/site-packages (2026.5.0)
Requirement already satisfied: google-api-core<3.0.0,>=2.11.1 in /opt/anaconda3/lib/python3.12/site-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (2.30.3)
Requirement already satisfied: google-auth<3.0.0,>=2.14.1 in /opt/anaconda3/lib/python3.12/site-packages (from google-cloud-bigquery) (2.53.0)
Requirement already satisfied: google-cloud-core<3.0.0,>=2.4.1 in /opt/anaconda3/lib/python3.12/site-packages (from google-cloud-bigquery) (2.6.0)
Requirement already satisfied: google-resumable-media<3.0.0,>=2.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from google-cloud-bigquery) (2.9.0)
Requirement already satisfied: packaging>=24.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from google-cloud-bigquery) (26.2)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.2 in /opt/anaconda3/lib/python3.12/site-packages (from google-cloud-bigquery) (2.9.0.post0)
Requirement already satisfied: requests<3.0.0,>=2.21.0 in /opt/anaconda3/lib/python3.12/site-packages (from google-cloud-bigquery) (2.32.2)
Requirement already satisfied: numpy>=1.24.0 in /opt/anaconda3/lib/python3.12/site-packages (from db-dtypes) (1.26.4)
Requirement already satisfied: pandas<3.0.0,>=1.5.3 in /opt/anaconda3/lib/python3.12/site-packages (from db-dtypes) (2.2.2)
Requirement already satisfied: pyarrow>=13.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from db-dtypes) (14.0.2)
Requirement already satisfied: setuptools in /opt/anaconda3/lib/python3.12/site-packages (from pandas-gbq) (69.5.1)
Requirement already satisfied: pydata-google-auth>=1.5.0 in /opt/anaconda3/lib/python3.12/site-packages (from pandas-gbq) (1.9.1)
Requirement already satisfied: psutil>=5.9.8 in /opt/anaconda3/lib/python3.12/site-packages (from pandas-gbq) (7.2.2)
Requirement already satisfied: google-auth-oauthlib>=0.7.0 in /opt/anaconda3/lib/python3.12/site-packages (from pandas-gbq) (1.4.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0 in /opt/anaconda3/lib/python3.12/site-packages (from gcsfs) (3.9.5)
Requirement already satisfied: decorator>4.1.2 in /opt/anaconda3/lib/python3.12/site-packages (from gcsfs) (5.1.1)
Requirement already satisfied: fsspec!=2026.4.0,>=2026.3.0 in /opt/anaconda3/lib/python3.12/site-packages (from gcsfs) (2026.3.0)
Requirement already satisfied: google-cloud-storage-control in /opt/anaconda3/lib/python3.12/site-packages (from gcsfs) (1.11.0)
Requirement already satisfied: google-cloud-storage>=3.9.0 in /opt/anaconda3/lib/python3.12/site-packages (from gcsfs) (3.10.1)
Requirement already satisfied: aiosignal>=1.1.2 in /opt/anaconda3/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->gcsfs) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in /opt/anaconda3/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->gcsfs) (23.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/anaconda3/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->gcsfs) (1.4.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/anaconda3/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->gcsfs) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in /opt/anaconda3/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->gcsfs) (1.9.3)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.63.2 in /opt/anaconda3/lib/python3.12/site-packages (from google-api-core<3.0.0,>=2.11.1->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (1.75.0)
Requirement already satisfied: protobuf<8.0.0,>=4.25.8 in /opt/anaconda3/lib/python3.12/site-packages (from google-api-core<3.0.0,>=2.11.1->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (6.33.6)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /opt/anaconda3/lib/python3.12/site-packages (from google-api-core<3.0.0,>=2.11.1->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (1.28.0)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /opt/anaconda3/lib/python3.12/site-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (1.80.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /opt/anaconda3/lib/python3.12/site-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (1.80.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/anaconda3/lib/python3.12/site-packages (from google-auth<3.0.0,>=2.14.1->google-cloud-bigquery) (0.2.8)
Requirement already satisfied: cryptography>=38.0.3 in /opt/anaconda3/lib/python3.12/site-packages (from google-auth<3.0.0,>=2.14.1->google-cloud-bigquery) (42.0.5)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /opt/anaconda3/lib/python3.12/site-packages (from google-auth-oauthlib>=0.7.0->pandas-gbq) (2.0.0)
Requirement already satisfied: google-crc32c<2.0.0,>=1.1.3 in /opt/anaconda3/lib/python3.12/site-packages (from google-cloud-storage>=3.9.0->gcsfs) (1.8.0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.12/site-packages (from pandas<3.0.0,>=1.5.3->db-dtypes) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.12/site-packages (from pandas<3.0.0,>=1.5.3->db-dtypes) (2023.3)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.12/site-packages (from python-dateutil<3.0.0,>=2.8.2->google-cloud-bigquery) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (2025.8.3)
Requirement already satisfied: grpc-google-iam-v1<1.0.0,>=0.14.0 in /opt/anaconda3/lib/python3.12/site-packages (from google-cloud-storage-control->gcsfs) (0.14.4)
Requirement already satisfied: cffi>=1.12 in /opt/anaconda3/lib/python3.12/site-packages (from cryptography>=38.0.3->google-auth<3.0.0,>=2.14.1->google-cloud-bigquery) (1.16.0)
Requirement already satisfied: typing-extensions~=4.12 in /opt/anaconda3/lib/python3.12/site-packages (from grpcio<2.0.0,>=1.33.2->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (4.15.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /opt/anaconda3/lib/python3.12/site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.14.1->google-cloud-bigquery) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.7.0->pandas-gbq) (3.3.1)
Requirement already satisfied: pycparser in /opt/anaconda3/lib/python3.12/site-packages (from cffi>=1.12->cryptography>=38.0.3->google-auth<3.0.0,>=2.14.1->google-cloud-bigquery) (2.21)

In [3]:
from google.cloud import bigquery
import pandas as pd

PROJECT_ID = "mdff-practicum-2026"
DATASET = "mdff"

client = bigquery.Client(project=PROJECT_ID)
print("Connected:", client.project)

Connected: mdff-practicum-2026

In [15]:
tables = list(client.list_tables("mdff-practicum-2026.mdff"))
inventory = [(t.table_id, t.full_table_id) for t in tables]
df_inventory = pd.DataFrame(inventory, columns=["table_name", "full_table_id"])
df_inventory = df_inventory.sort_values("table_name").reset_index(drop=True)
df_inventory

,table_name,full_table_id
0,DECEASED_DONOR_DATA,mdff-practicum-2026:mdff.DECEASED_DONOR_DATA
1,DECEASED_DONOR_DCD_MEASURES,mdff-practicum-2026:mdff.DECEASED_DONOR_DCD_ME...
2,DECEASED_DONOR_FORMATS_FLATFILE,mdff-practicum-2026:mdff.DECEASED_DONOR_FORMAT...
3,DECEASED_DONOR_INOTROPIC_MEDS,mdff-practicum-2026:mdff.DECEASED_DONOR_INOTRO...
4,IE_DATA,mdff-practicum-2026:mdff.IE_DATA
...,...,...
66,txf_ki,mdff-practicum-2026:mdff.txf_ki
67,txf_kp,mdff-practicum-2026:mdff.txf_kp
68,txf_li,mdff-practicum-2026:mdff.txf_li
69,txf_lu,mdff-practicum-2026:mdff.txf_lu
70,txf_pa,mdff-practicum-2026:mdff.txf_pa

In [17]:
rows = []
for t in tables:
    full = client.get_table(t.reference)
    rows.append((full.table_id, full.num_rows, round(full.num_bytes / 1e6, 1)))

df_inventory = pd.DataFrame(rows, columns=["table_name", "row_count", "size_mb"])
df_inventory = df_inventory.sort_values("row_count", ascending=False).reset_index(drop=True)
df_inventory

                       table_name  row_count  size_mb
0           KIDPAN_WLHISTORY_DATA   47016205  12048.5
1                      fol_immuno    9262786    435.1
2     KIDPAN_IMMUNO_FOLLOWUP_DATA    5514999   2534.9
3            KIDNEY_FOLLOWUP_DATA    5134196   1019.0
4                          txf_ki    5076988    909.6
..                            ...        ...      ...
66                    institution        724      0.1
67  LIVING_DONOR_FORMATS_FLATFILE        517      0.0
68                   hist_opo_txc        446      0.0
69         NON_RECOV_DCD_MEASURES        425      0.0
70       NON_RECOV_INOTROPIC_MEDS        200      0.0

[71 rows x 3 columns]

In [5]:
tables = list(client.list_tables(f"{PROJECT_ID}.{DATASET}"))
rows = []
for t in tables:
    full = client.get_table(t.reference)
    rows.append((full.table_id, full.num_rows, round(full.num_bytes / 1e6, 1)))

df_inventory = pd.DataFrame(rows, columns=["table_name", "row_count", "size_mb"])
df_inventory = df_inventory.sort_values("row_count", ascending=False).reset_index(drop=True)
df_inventory

                       table_name  row_count  size_mb
0           KIDPAN_WLHISTORY_DATA   47016205  12048.5
1                      fol_immuno    9262786    435.1
2     KIDPAN_IMMUNO_FOLLOWUP_DATA    5514999   2534.9
3            KIDNEY_FOLLOWUP_DATA    5134196   1019.0
4                          txf_ki    5076988    909.6
..                            ...        ...      ...
66                    institution        724      0.1
67  LIVING_DONOR_FORMATS_FLATFILE        517      0.0
68                   hist_opo_txc        446      0.0
69         NON_RECOV_DCD_MEASURES        425      0.0
70       NON_RECOV_INOTROPIC_MEDS        200      0.0

[71 rows x 3 columns]

In [7]:
query = """
SELECT *
FROM `mdff-practicum-2026.mdff.cand_kipa`
LIMIT 5
"""
df = client.query(query).to_dataframe()
df.head()

/opt/anaconda3/lib/python3.12/site-packages/google/cloud/bigquery/table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

,PERS_ID,PX_ID,WL_ORG,CAN_GENDER,CAN_ABO,CAN_RACE,CAN_RACE_SRTR,CAN_ETHNICITY_SRTR,DON_TY,REC_TX_PROCEDURE_TY,...,CAN_INIT_ACT_STAT_DT,CAN_INIT_INACT_STAT_DT,CAN_LAST_ACT_STAT_DT,CAN_LAST_INACT_STAT_DT,CAN_INIT_ACT_STAT_CD,PERS_NEXTTX,PERS_NEXTTX_TRR_ID,CAN_TRR_EXISTS,CAN_PAIRED_LIVE_DONOR_ID,DONOR_ID
0,5191145.0,1318333.0,KI,F,A,None,WHITE,LATINO,None,None,...,None,2020-01-10,None,2021-03-27,None,None,None,0.0,None,None
1,8393025.0,1306510.0,KI,M,O,None,WHITE,LATINO,None,None,...,2019-11-01,None,2023-02-09,None,4010.0,None,None,0.0,None,None
2,8417206.0,1328303.0,KI,M,O,8.0,WHITE,NLATIN,None,None,...,None,2020-03-04,None,2021-06-17,None,None,None,0.0,None,None
3,8402511.0,1311878.0,KI,F,O,8.0,WHITE,NLATIN,None,None,...,2019-12-02,2021-09-02,2021-09-01,2024-11-13,4010.0,None,None,0.0,None,None
4,8416443.0,1332839.0,KI,M,O,8.0,WHITE,NLATIN,None,None,...,2020-03-27,None,2023-03-03,None,4010.0,2023-02-26,988262.0,0.0,None,None